behaviors:
  PewPew:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 2.0e-4
      beta: 5.5e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 4
      use_curiosity: true
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 10000
environment_parameters:
  BossNumber:
    curriculum:
      - name: LearnToShoot # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: EndDistance
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
          require_reset: true
        value: 0.0
      - name: DontGetShot
        completion_criteria:
          measure: progress
          behavior: BulletsDodged
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
          require_reset: true
        value: 1.0
      - name: LearnToDodge_VeryEasy
        completion_criteria:
          measure: progress
          behavior: DamageDealt
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
          require_reset: true
        value: 2.0
      - name: LearnToDodge_Easy
        completion_criteria:
          measure: progress
          behavior: EndDistance
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
          require_reset: true
        value: 3.0
      - name: LearnToDodge_Medium
        completion_criteria:
          measure: progress
          behavior: DamageDealt
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
          require_reset: true
        value: 4.0
      - name: LearnToDodge_Hard
        completion_criteria:
          measure: progress
          behavior: DamageDealt
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
          require_reset: true
        value: 5.0
      - name: LearnToDodge_Harder
        completion_criteria:
          measure: progress
          behavior: DamageDealt
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
          require_reset: true
        value: 6.0
      - name: LearnToDodge_VeryHard
        completion_criteria:
          measure: progress
          behavior: DamageDealt
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
          require_reset: true
        value: 7.0
      - name: LearnToDodge_Hardest
        completion_criteria:
          measure: progress
          behavior: DamageDealt
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.1
          require_reset: true
        value: 2.0